### ISSUE TITLE
اپدیت package_info_plus

### ISSUE THREAD

**Issue by m2faridi** [ali2236/iran_appmarket#1]
سلام لطفا نسخه package_info_plus را ارتقا دهید
ارور میده در نسخه جدید

**Comment by ali2236** [comment]
سلام اصلاح شد

**Comment by m2faridi** [comment]
سلام مجدد نیاز به ابدیت این کتابخونه هست

**Comment by ali2236** [comment]
سلام. با پشتیبانی از دارت 3، جدیدترین نسخه کتابخانه‌ها و حذف کدهای اندروید قدیمی، آپدیت شد.
